# Generated by Django 3.1.4 on 2021-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
