# Generated by Django 3.1.4 on 2021-05-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210524_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
    ]
